version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: ziwoniyfy-admin-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ziwoni
      MONGO_INITDB_ROOT_PASSWORD: 212131
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
